### ISSUE TITLE
Upload not working for files with size over chunksize

### ISSUE THREAD

**Issue by drJeckyll** [cubiclesoft/js-fileexplorer#10]
I'm using lighttpd 1.4.59 with PHP 7.4.27 on Gentoo Linux. 

When I try to upload file with size over chunksize (in my case it seems to be 1MB), final stage of upload never happened. File is actually  uploaded in full size, but stay with .tmp extension. 

Removing .tmp and comparing file with original it's seems identical. If I put fixed chunksize to some very large number like 100GB for example make upload to work.

**Comment by gstrauss** [comment]
lighttpd 1.4.64 was recently released, so lighttpd 1.4.59 is more than a few releases old.  Please test with the latest lighttpd release and report if there is still an issue.

**Comment by cubiclesoft** [comment]
I was able to replicate the issue on my end and have fixed the problem (lighttpd had nothing to do with it).  I forgot that PHP caches stats.  Clearing the PHP stat cache before checking file size after processing the last chunk solves the temp file problem.

I recommend keeping chunk size fairly small per request to keep system resource usage low (maybe no more than 10MB).  Also, when file data is sent in chunks, the chunk size must be smaller than the configured maximum file upload size for PHP.  Chunks also allow progress to be tracked more easily across browsers.  PHP itself has a default maximum POST size AND maximum file upload size in the INI configuration file, whichever is smaller.  Sending data in chunks allows PHP INI limits to be exceeded.  File data sent via POST request is Base64 encoded, so you also need to include a 33% increase of data sent to the server into your calculations.

The `FileUploadHelper::GetMaxUploadFileSize()` function in `server-side-helpers/file_upload_helper.php` calculates and returns the maximum upload chunk size possible in bytes minus space for a 4KB POST buffer for other info.

At any rate, the underlying problem has now been fixed.  Please update to the latest version of the files in this repo.
