### ISSUE TITLE
What are js-fileexplorer differences from WebDAV?

### ISSUE THREAD

**Issue by gstrauss** [cubiclesoft/js-fileexplorer#11]
What are js-fileexplorer differences from WebDAV?

I am a lighttpd developer and lighttpd natively supports WebDAV with lighttpd mod_webdav.  Files and folders can be manipulated in MacOS, Windows, Linux, and others using the client OS native file interfaces (as long as they support the WebDAV protocol)

I am curious where js-fileexplorer has advantages, and if these advantages are over the client OS WebDAV implementations or if there is something that lighttpd can do better on the server side.

**Comment by cubiclesoft** [comment]
This is a pure Javascript widget for any web app/interface.  It is up to the implementer on how it interfaces with their backend and application.  It can be a view of a hierarchical database for all it cares. which is something I leveraged myself last year when I added Scan Explorer to [File Tracker](https://file-tracker.cubiclesoft.com/) for significant improvements in dependency management.  There are advantages to having an in-browser navigable interface that works on all devices.

WebDAV is a protocol.  It's not related to this project.
