### ISSUE TITLE
Hide options (cut, upload, download) if they are disabled.

### ISSUE THREAD

**Issue by mrkacg1** [cubiclesoft/js-fileexplorer#15]
If I disable upload, the button is still there unnecessarily. Although a file cannot be uploaded, it may confuse the user.

**Comment by cubiclesoft** [comment]
Don't include any code for features you don't need.  Buttons are only added when a function is defined either at initialization, using the specific event listener, or explicitly specifying the button.

**Comment by mrkacg1** [comment]
Can you please tell me where this could be changed? Thank you for this nice app,

**Comment by cubiclesoft** [comment]
Set the "canmodify" option for the folder to false.

**Comment by mrkacg1** [comment]
Thanks.
