### ISSUE TITLE
Feature: Add a package.json for importing into npm projects

### ISSUE THREAD

**Issue by jonshipman** [cubiclesoft/js-fileexplorer#16]
PR incoming

**Comment by jonshipman** [comment]
The idea is with a package.json, when you want to include js-fileexplorer, you can add it like so: 

```npm i git+https://git@github.com/cubiclesoft/js-fileexplorer.git```

Ideally you would publish to the npm repo, but not required. No code changes in this PR so the package would still be used the same, e.g. calling new window.FileExplorer.

The benefit is that projects depending on js-fileexplorer will be referencing back to this repo as opposed to now where it needs to be copied into a project.

**Comment by cubiclesoft** [comment]
Done.  Closing.
