### ISSUE TITLE
there is no way to upload files using other transport method than built-in method

### ISSUE THREAD

**Issue by mikk150** [cubiclesoft/js-fileexplorer#19]
I would like to do everything using Axios, unfortunately oninitupload does not have a way to tell this plugin that upload has finished

perfect way would be that every event should have promise

**Comment by cubiclesoft** [comment]
The documentation says:

* oninitupload(startupload, fileinfo, queuestarted) - An optional callback function that is called when the user clicks the Upload icon or presses Ctrl + U.
	* startupload(fileinfo, process) - A callback function to call upon completion of initializing the upload or on failure.  **The 'process' option can be used to tell the callback to process the upload itself or skip it if it was handled in the callback** (e.g. creating an empty directory).  When 'process' is a string, it is treated as an error message to display to the user.
	* fileinfo - The file information object of the file to initialize for uploading.
	* queuestarted - An integer containing a UNIX timestamp of when the current upload queue was started.  Can be useful to pass to a server that can use the value to copy files that are going to be overwritten to a recycling bin folder before the overwrite happens.

Unless I'm missing something, you should be able to call `startupload()` and pass `false` for the process parameter after handling the upload via Axios.  I knew some people would not want to use the built-in upload handler when I created the widget.  You can also pass an error message back to the widget for it to display via the `process` parameter.

**Comment by mikk150** [comment]
@cubiclesoft reopen as yes, I can call `startupload()` and pass `false`, but now it does not show progress of uploading

**Comment by cubiclesoft** [comment]
When you call startupload() with false, then it is your responsibility to handle the upload including any upload indicators/dialogs/etc.  You are telling the widget that you are or have handled everything related to the upload.
