### ISSUE TITLE
How to get file object for file upload?

### ISSUE THREAD

**Issue by kla-ko** [cubiclesoft/js-fileexplorer#20]
I didn't get the mechanism of how to  upload a file. The function for ``oninitupload`` receives a ``fileinfo`` object.
However, this object does not contain the full path to the file on my local drive. I expected to receive something like a ``File``-object as provided by a file input element like ``<input type="file" id="fileInput" />``

Any help will be appreciated
Thanks

**Comment by kla-ko** [comment]
Think I got it working ...

**Comment by reke-buchenau** [comment]
> Think I got it working ...

Hi kla-ko,

how do you resolve this?

Thank you in advance

**Comment by kla-ko** [comment]
I have an API to upload the file and I'm passing ``fileinfo.file`` to this API. This made it.

**Comment by cubiclesoft** [comment]
`fileinfo.file` is indeed the correct way to access the raw File object if you are handling the upload yourself.  The property name is considered stable.

I've updated `demo.html` with a comment about the property.
