### ISSUE TITLE
How to use without php?

### ISSUE THREAD

**Issue by jomin398** [cubiclesoft/js-fileexplorer#23]
I have a json to describing directories.
I want to use it without php server. (Only frontend)
how to emulate prepXhr with json file or object?
```
[
{n: "folder1",
icon:"cloudFolder",
url:"./folder1"
}
]
```

**Comment by anyoneoruser** [comment]
I tried the same think for a system that store the files in the client's browser. In the reality, you are not in the obligation to use PrepareXHR, you can create your own files representation system like and manage the interface events to make it compatible with the entries structure.
This is my format:
```javascript
{
   path:"/a/very/long/path/to/the/file.txt",
   mimetype:"mime/type",
   content:"Hello world !"
}
```

**Comment by cubiclesoft** [comment]
Yes.  You can definitely mock responses back into the widget.  While the most obvious integration is with a server, there is no obligation/requirement to use server-side communications or even the included PrepareXHR handler.  There's also no requirement to use PHP on the server side of things.
