### ISSUE TITLE
Thumnail for video files?

### ISSUE THREAD

**Issue by AirplanegoBrr** [cubiclesoft/js-fileexplorer#24]
Is this a thing? Is it possible?

**Comment by cubiclesoft** [comment]
It's possible.  You just have to read the video file container formats you are interested in and extract an embedded thumbnail and put the image into a folder and then tell the widget where the thumbnail is at.  Reading video file formats is its own challenge.  And if you are looking for something more advanced than that (e.g. extract a thumbnail from a video itself) then you'll need to run a tool like ffmpeg.  While these things are technically possible, you are generally on your own on the implementation.
