### ISSUE TITLE
License request

### ISSUE THREAD

**Issue by noirscape** [cubiclesoft/js-fileexplorer#6]
Hello, I'd like to use this project in one of my (FOSS) programs. Could I ask you if it would be possible to get a compatible license for this in the repository? Right now there is no indicator as to what the license is, which means it goes under GitHubs default licensing, which isn't great.

**Comment by noirscape** [comment]
Correction, I just saw in the readme it's either MIT/GPL. Sorry for bothering your time and thanks a boatload for the project!

**Comment by cubiclesoft** [comment]
It's actually your choice of MIT or LGPL.

GPL is copyleft and causes problems while LGPL does not have as many issues.  Just clarifying in case someone runs into this issue on the issue tracker.

No worries and you're welcome!
