### ISSUE TITLE
Cool project.

### ISSUE THREAD

**Issue by giannik** [cubiclesoft/js-fileexplorer#7]
This looks great.
I would like to integrate with a backend file server on windows using c# and .net core framework.
I guess this can be done since I am comfortable with c# . Right ?
Thanks 
giannis

**Comment by cubiclesoft** [comment]
This project provides a Javascript component intended for use in a web browser environment on the client side of things.  As such, the backend server shouldn't matter.  So to answer the question, yes, ASP.NET code written in C# should be fine.

You might want to use the sample PHP server-side helper class as a possible guide/approach for your integration.  There are a number of nuances to working with this component and you don't want to accidentally introduce security vulnerabilities on the server side of things.

Closing this issue as it is not a bug/feature request.
