### ISSUE TITLE
How to empty recycle bin?

### ISSUE THREAD

**Issue by charles-velosure** [cubiclesoft/js-fileexplorer#8]
Hi there,

I found that I could not delete any files in Recycle Bin or empty the bin. 

![image](https://user-images.githubusercontent.com/85481883/147615988-873bf6db-e1de-4f76-9763-760ad9b93cab.png)

Is there any options for me to allow permanently deleting items in Recycle Bin or empty Recycle Bin?

**Comment by cubiclesoft** [comment]
The recycling bin is intended to be cleaned out automatically on some sort of schedule.  You should write a separate script for your application to locate old directories in the recycling bin (e.g. more than 7 days old) and remove them.

The recycling bin feature is optional.  It's designed to prevent users from permanently deleting files off the system only to realize two minutes later that they deleted the wrong file and they don't have a backup.
