### ISSUE TITLE
Skin / design contribution

### ISSUE THREAD

**Issue by contactjavas** [cubiclesoft/js-fileexplorer#9]
Hi @cubiclesoft , are you open to design / skin contribution?
The functionality works great. I think it will be awesome if we can improve the skin/design :)

**Comment by cubiclesoft** [comment]
Anyone is free to fork and make changes.  That's kind of the point of open source software.

Whether or not I'll accept changes back into the main branch varies.  For something akin to dark mode, I'd be open to that on the main branch but there are restrictions (e.g. icons) on what I would allow.  I'm not necessarily as open to modifications of the existing CSS/image file.

All other skins/themes are better off in their own separate repository.  I'd be okay with linking to significantly different themes from the main repo.
